//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acme.Protocol.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AcmeProtocolShared {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AcmeProtocolShared() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Acme.Protocol.Resources.AcmeProtocolShared", typeof(AcmeProtocolShared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AlgorithmCannotBeEmpty {
            get {
                return ResourceManager.GetString("AlgorithmCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string UnsupportedJwsAlgorithm {
            get {
                return ResourceManager.GetString("UnsupportedJwsAlgorithm", resourceCulture);
            }
        }
        
        internal static string UnsupportedAlgorithm {
            get {
                return ResourceManager.GetString("UnsupportedAlgorithm", resourceCulture);
            }
        }
        
        internal static string UrlCannotBeEmpty {
            get {
                return ResourceManager.GetString("UrlCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string InvalidUrlFormat {
            get {
                return ResourceManager.GetString("InvalidUrlFormat", resourceCulture);
            }
        }
        
        internal static string ComputeThumbprintMissingKty {
            get {
                return ResourceManager.GetString("ComputeThumbprintMissingKty", resourceCulture);
            }
        }
        
        internal static string ComputeThumbprintMissingK {
            get {
                return ResourceManager.GetString("ComputeThumbprintMissingK", resourceCulture);
            }
        }
        
        internal static string SignDataCannotBeEmpty {
            get {
                return ResourceManager.GetString("SignDataCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string SignMissingK {
            get {
                return ResourceManager.GetString("SignMissingK", resourceCulture);
            }
        }
        
        internal static string VerifyDataCannotBeEmpty {
            get {
                return ResourceManager.GetString("VerifyDataCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string VerifySignatureCannotBeEmpty {
            get {
                return ResourceManager.GetString("VerifySignatureCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string VerifyMissingK {
            get {
                return ResourceManager.GetString("VerifyMissingK", resourceCulture);
            }
        }
        
        internal static string RsaComputeThumbprintMissingKty {
            get {
                return ResourceManager.GetString("RsaComputeThumbprintMissingKty", resourceCulture);
            }
        }
        
        internal static string RsaComputeThumbprintMissingN {
            get {
                return ResourceManager.GetString("RsaComputeThumbprintMissingN", resourceCulture);
            }
        }
        
        internal static string RsaComputeThumbprintMissingE {
            get {
                return ResourceManager.GetString("RsaComputeThumbprintMissingE", resourceCulture);
            }
        }
        
        internal static string RsaSignDataCannotBeEmpty {
            get {
                return ResourceManager.GetString("RsaSignDataCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string RsaSignMissingN {
            get {
                return ResourceManager.GetString("RsaSignMissingN", resourceCulture);
            }
        }
        
        internal static string RsaSignMissingE {
            get {
                return ResourceManager.GetString("RsaSignMissingE", resourceCulture);
            }
        }
        
        internal static string RsaSignMissingD {
            get {
                return ResourceManager.GetString("RsaSignMissingD", resourceCulture);
            }
        }
        
        internal static string RsaSignMissingP {
            get {
                return ResourceManager.GetString("RsaSignMissingP", resourceCulture);
            }
        }
        
        internal static string RsaSignMissingQ {
            get {
                return ResourceManager.GetString("RsaSignMissingQ", resourceCulture);
            }
        }
        
        internal static string RsaSignMissingDp {
            get {
                return ResourceManager.GetString("RsaSignMissingDp", resourceCulture);
            }
        }
        
        internal static string RsaSignMissingDq {
            get {
                return ResourceManager.GetString("RsaSignMissingDq", resourceCulture);
            }
        }
        
        internal static string RsaSignMissingQi {
            get {
                return ResourceManager.GetString("RsaSignMissingQi", resourceCulture);
            }
        }
        
        internal static string RsaVerifyDataCannotBeEmpty {
            get {
                return ResourceManager.GetString("RsaVerifyDataCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string RsaVerifySignatureCannotBeEmpty {
            get {
                return ResourceManager.GetString("RsaVerifySignatureCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string RsaVerifyMissingN {
            get {
                return ResourceManager.GetString("RsaVerifyMissingN", resourceCulture);
            }
        }
        
        internal static string RsaVerifyMissingE {
            get {
                return ResourceManager.GetString("RsaVerifyMissingE", resourceCulture);
            }
        }
        
        internal static string EcComputeThumbprintMissingKty {
            get {
                return ResourceManager.GetString("EcComputeThumbprintMissingKty", resourceCulture);
            }
        }
        
        internal static string EcComputeThumbprintMissingCrv {
            get {
                return ResourceManager.GetString("EcComputeThumbprintMissingCrv", resourceCulture);
            }
        }
        
        internal static string EcComputeThumbprintMissingX {
            get {
                return ResourceManager.GetString("EcComputeThumbprintMissingX", resourceCulture);
            }
        }
        
        internal static string EcComputeThumbprintMissingY {
            get {
                return ResourceManager.GetString("EcComputeThumbprintMissingY", resourceCulture);
            }
        }
        
        internal static string EcSignDataCannotBeEmpty {
            get {
                return ResourceManager.GetString("EcSignDataCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string EcSignMissingCrv {
            get {
                return ResourceManager.GetString("EcSignMissingCrv", resourceCulture);
            }
        }
        
        internal static string EcSignMissingX {
            get {
                return ResourceManager.GetString("EcSignMissingX", resourceCulture);
            }
        }
        
        internal static string EcSignMissingY {
            get {
                return ResourceManager.GetString("EcSignMissingY", resourceCulture);
            }
        }
        
        internal static string EcSignMissingD {
            get {
                return ResourceManager.GetString("EcSignMissingD", resourceCulture);
            }
        }
        
        internal static string EcVerifyDataCannotBeEmpty {
            get {
                return ResourceManager.GetString("EcVerifyDataCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string EcVerifySignatureCannotBeEmpty {
            get {
                return ResourceManager.GetString("EcVerifySignatureCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string EcVerifyMissingCrv {
            get {
                return ResourceManager.GetString("EcVerifyMissingCrv", resourceCulture);
            }
        }
        
        internal static string EcVerifyMissingX {
            get {
                return ResourceManager.GetString("EcVerifyMissingX", resourceCulture);
            }
        }
        
        internal static string EcVerifyMissingY {
            get {
                return ResourceManager.GetString("EcVerifyMissingY", resourceCulture);
            }
        }
        
        internal static string EnumNameNotFound {
            get {
                return ResourceManager.GetString("EnumNameNotFound", resourceCulture);
            }
        }
        
        internal static string EnumDisplayNameNotFound {
            get {
                return ResourceManager.GetString("EnumDisplayNameNotFound", resourceCulture);
            }
        }
        
        internal static string EnumDisplayDescriptionNotFound {
            get {
                return ResourceManager.GetString("EnumDisplayDescriptionNotFound", resourceCulture);
            }
        }
        
        internal static string UnsupportedIdentifierType {
            get {
                return ResourceManager.GetString("UnsupportedIdentifierType", resourceCulture);
            }
        }
        
        internal static string InvalidContactFormat {
            get {
                return ResourceManager.GetString("InvalidContactFormat", resourceCulture);
            }
        }
        
        internal static string UnsupportedContactType {
            get {
                return ResourceManager.GetString("UnsupportedContactType", resourceCulture);
            }
        }
        
        internal static string LinkHeaderNullOrEmpty {
            get {
                return ResourceManager.GetString("LinkHeaderNullOrEmpty", resourceCulture);
            }
        }
        
        internal static string InvalidLinkHeaderFormat {
            get {
                return ResourceManager.GetString("InvalidLinkHeaderFormat", resourceCulture);
            }
        }
        
        internal static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
    }
}
